import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { InsightStageTabs } from "@/components/insights/insight-stage-tabs";
import { getShare } from "@/lib/dynamodb/repositories/insight-shares";
import { getInsight } from "@/lib/dynamodb/repositories/insights";
import { getProject } from "@/lib/dynamodb/repositories/projects";
import { notFound } from "next/navigation";

export const metadata = { title: "NIS — Shared insight" };

export default async function SharedInsightPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  const share = await getShare(token);
  if (!share) notFound();
  if (share.expiresAt && share.expiresAt * 1000 < Date.now()) notFound();

  const [insight, project] = await Promise.all([
    getInsight(share.projectId, share.sk),
    getProject(share.projectId),
  ]);
  if (!insight || !project) notFound();
  if (insight.shareToken !== token) notFound();

  return (
    <main className="mx-auto min-h-screen w-full max-w-5xl p-6 md:p-10">
      <div className="mb-6 flex items-center justify-between">
        <div>
          <div className="text-[10px] font-medium uppercase tracking-[0.25em] text-slate-500">
            NIS shared insight
          </div>
          <h1 className="mt-1 text-2xl font-semibold text-white">{project.projectName}</h1>
          <p className="text-xs text-slate-400">
            {insight.period.start} 〜 {insight.period.end}
            {insight.modelProvider
              ? ` · ${insight.modelProvider === "claude" ? "Claude (Bedrock)" : "Gemini"}`
              : ""}
          </p>
        </div>
        <Badge tone="ai">Read-only shared view</Badge>
      </div>

      <Card className="glow-border">
        <p className="text-sm leading-relaxed text-slate-200">{insight.summary}</p>
        <div className="mt-4 rounded-lg border border-white/10 bg-white/5 p-4">
          <div className="text-xs font-semibold uppercase tracking-wide text-slate-400">
            Top priority
          </div>
          <p className="mt-2 text-sm text-white">{insight.topPriority.action}</p>
          <p className="mt-1 text-xs text-slate-500">{insight.topPriority.reason}</p>
        </div>
      </Card>

      {insight.pipeline ? (
        <InsightStageTabs pipeline={insight.pipeline} />
      ) : (
        <div className="mt-6 space-y-4">
          {insight.findings.map((f) => (
            <Card key={f.title}>
              <div className="flex flex-wrap items-center gap-2">
                <Badge tone="ai">{f.category}</Badge>
                <Badge tone={f.severity === "high" ? "danger" : "neutral"}>{f.severity}</Badge>
              </div>
              <h2 className="mt-3 text-lg font-semibold text-white">{f.title}</h2>
              <p className="mt-2 text-sm text-slate-300">{f.observation}</p>
              <p className="mt-2 text-sm text-slate-400">仮説: {f.hypothesis}</p>
              {f.risk ? <p className="mt-2 text-sm text-rose-200/90">リスク: {f.risk}</p> : null}
              <ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-cyan-100/90">
                {f.actions.map((a) => (
                  <li key={a}>{a}</li>
                ))}
              </ul>
            </Card>
          ))}
        </div>
      )}

      <p className="mt-10 text-center text-[10px] text-slate-600">
        Generated by NIS · Shared link is read-only.
      </p>
    </main>
  );
}
